-- 시퀀스 생성

CREATE SEQUENCE join_id_seq;
CREATE SEQUENCE party_id_seq;
CREATE SEQUENCE report_id_seq;

 
 -- 참여
 
  CREATE TABLE "JOIN" 
   (	"JOIN_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"PARTY_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"MEMBER_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"CONTENTS" VARCHAR2(500 BYTE) NOT NULL ENABLE, 
	"CRETED_AT" TIMESTAMP (6) DEFAULT sysdate NOT NULL ENABLE, 
	"STATUS" VARCHAR2(100 BYTE) DEFAULT '대기' NOT NULL ENABLE, 
	 CONSTRAINT "JOIN_PK" PRIMARY KEY ("JOIN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  

-- 회원  
  
    CREATE TABLE "MEMBER" 
   (	"MEMBER_ID" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"PW" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"NAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"NICKNAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"AGE" NUMBER(*,0) NOT NULL ENABLE, 
	"GENDER" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"JUMIN" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"PHONE" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"PHOTO" VARCHAR2(100 BYTE), 
	 CONSTRAINT "MEMBER_PK" PRIMARY KEY ("MEMBER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;


-- 모임
  
    CREATE TABLE "PARTY" 
   (	"PARTY_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"MEMBER_ID" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"FOOD_CATEGORY" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"LOCAL_CATEGORY" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"SUBJECT" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"CONTENTS" VARCHAR2(3000 BYTE) NOT NULL ENABLE, 
	"ADDRESS" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"MEALED_AT" TIMESTAMP (6) NOT NULL ENABLE, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT sysdate NOT NULL ENABLE, 
	"THUMBNAIL" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"LIMITNUM" NUMBER(*,0) NOT NULL ENABLE, 
	"STATUS" VARCHAR2(100 BYTE) DEFAULT '일반' NOT NULL ENABLE, 
	 CONSTRAINT "PARTY_PK" PRIMARY KEY ("PARTY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  
-- 신고
  
    CREATE TABLE "REPORT" 
   (	"REPORT_ID" NUMBER(*,0), 
	"MEMBER_ID" VARCHAR2(100 BYTE), 
	"PARTY_ID" NUMBER(*,0), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;